### ISSUE TITLE
Render error env on yaml

### ISSUE THREAD

**Issue by psyreactor** [shyiko/kubetpl#15]
Hello,
Sorry for my English, I speak Spanish.
I get the following error. env depends on containers. But it should depend on image.

Result:
```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-app
  namespace: java-app
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java
        tipo: api-rest
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Dspring.profiles.active=staging
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: spring.datasource.username
              name: java-app-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: spring.datasource.password
              name: java-app-secret
        image: docker.hub/java-app:1.0
        imagePullPolicy: IfNotPresent
        imagePullSecrets:
        - name: java-app-reg
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: java-app
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/logs/
          name: logs-volume
      volumes:
      - emptyDir: {}
        name: logs-volume
```
template:
```yaml
# kubetpl:syntax:go-template
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .APP_NAME }}
  namespace: {{ .NAMESPACE_NAME }}
spec:
  replicas: {{ get "REPLICAS" 1 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
      {{ range $index, $value := .LABELS }}
        {{ $index | indent 8 }}: {{ $value }}
      {{ end }}
    spec:
      containers:
        - image: {{ .REGISTRY_IMAGE }}:{{ .IMAGE_VERSION }}
          name: {{ .APP_NAME }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/logs/
              name: logs-volume
          env:
            - name: JAVA_OPTS
              value: -Dspring.profiles.active=staging
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .APP_NAME }}-secret
                  key: spring.datasource.username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .APP_NAME }}-secret
                  key: spring.datasource.password
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            failureThreshold: 12
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: "1024Mi"
          imagePullSecrets:
            - name: {{ .APP_NAME }}-reg
      volumes:
        - emptyDir: {}
          name: logs-volume
```
env.json:
```json
{
  "APP_NAME": "java-app",
  "NAMESPACE_NAME": "java-app",
  "REPLICAS": "2",
  "REGISTRY_IMAGE": "docker.hub/java-app",
  "IMAGE_VERSION": "1.0",
  "REGISTRY_SECRET": "eyJhdXRocyI6eyJyZWdpcaljfsdmsdA3FdW3ecEFWdedwwedEFSFQwqdkewDEdWEDewDwed3RyeS5uZy5ibHVlbWl4Lm5ldCI6eyJ1c2VybmFtZSI6InRva2VuIiwicGFzc3dvcmQiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcWRHa2lPaUkwTldWaU5URm1aUzA0TVdReExUVXhPRE10T1RCa1ppMWlNakZsWWpOa01EZGhaRFVpTENKcGMzTWlPaUp5WldkcGMzUnllUzV1Wnk1aWJIVmxiV2w0TG01bGRDSjkudDJoNXI4SXJaZ3d0STFSYlVrQVJIWXdQemViSXZ2amVnZ1g0Sl8wakVZMCIsImVtYWlsIjoiZ2FicmllbC5tZWxpYW5Ac3VwZXJ2aWVsbGUuY29tLmFyIiwiYXV0aCI6ImRHOXJaVzQ2WlhsS2FHSkhZMmxQYVVwSlZYcEpNVTVwU1hOSmJsSTFZME5KTmtscmNGaFdRMG81TG1WNVNuRmtSMnRwVDJsSk1FNVhWbWxPVkVadFdsTXdORTFYVVhoTVZGVjRUMFJOZEU5VVFtdGFhVEZwVFdwR2JGbHFUbXROUkdSb1drUlZhVXhEU25Cak0wMXBUMmxLZVZwWFpIQmpNMUo1WlZNMWRWcDVOV2xpU0Zac1lsZHNORXh0Tld4a1EwbzVMblF5YURWeU9FbHlXbWQzZEVreFVtSlZhMEZTU0ZsM1VIcGxZa2wyZG1wbFoyZFlORXBmTUdwRldUQT0ifX19",
  "LABELS": {
    "app":"java",
    "tipo":"api-rest"
    }
  }
```
I do not detect anything erroneous in the config.
Best regards.

**Comment by shyiko** [comment]
```bash
$ kubetpl r template.yml -i env.json | kubeval
The document stdin contains a valid Deployment
```
Can you please specify what kind of error are you getting (command + error output)? Thanks.

**Comment by psyreactor** [comment]
Hi shyiko,
No error occurs but the output is not as expected.
the env label depends on containers.

output:
```yaml
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Dspring.profiles.active=staging
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: spring.datasource.username
              name: java-app-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: spring.datasource.password
              name: java-app-secret
        image: docker.hub/java-app:1.0
        imagePullPolicy: IfNotPresent
        imagePullSecrets:
```

The label env has to depend on image no of containers.
And you should not have "-" at the beginning
 
Expected output:
```yaml
    spec:
      containers:
        - image: docker.hub/java-app:1.0
          name: java-app
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/logs/
              name: logs-volume
          env:
            - name: JAVA_OPTS
              value: -Dspring.profiles.active=staging
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: java-app-secret
                  key: spring.datasource.username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: java-app-secret
                  key: spring.datasource.password
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
```

command execute:
```bash
kubetpl render Deployment.yaml -i test.json
```
kubetpl --version 0.9.0

Regards
