### ISSUE TITLE
A more complex type of substitution.

### ISSUE THREAD

**Issue by timuckun** [shyiko/kubetpl#16]
Say I have the following env vars.

```bash
export APP_ENV='development'
export development_DB="dev.db.com"
export production_DB=prod.db.com
```

I want to render the following in my yaml file.
```yaml
    env:
          - name: DB
             value: ${${APP_ENV}_DB}
```

I know the syntax is not valid bash but I hope you know what I mean. 

Thanks.
