### ISSUE TITLE
numbers in quotes are being converted to numbers instead of being left as strings

### ISSUE THREAD

**Issue by codeliger** [shyiko/kubetpl#24]
```yml
  environment: development
  webtitan:
    customer_id: "1"
```

Parsing this yml with kubetpl passes the value as a literal 1 into a ConfigMap which fails to parse in kubernetes

This is unexpected behaviour and a string should be passed if a string is specified
