### ISSUE TITLE
Resource with 'parameters' key and no syntax "cannot unmarshal !!map into []engine.TemplateKindTemplateParameter"

### ISSUE THREAD

**Issue by krbcmt** [shyiko/kubetpl#33]
Issue type: Bug

Given a kubernetes resource file that has a top-level key `parameters` and no syntax definition as a comment nor command-line argument a fatal unmarshal error occurs.

Example **resource.yml**:

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-delete-bucket
provisioner: ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: ceph-object-store
  objectStoreNamespace: rook-ceph
```
```
$ kubetpl render resource.yml
yaml: unmarshal errors:
  line 8: cannot unmarshal !!map into []engine.TemplateKindTemplateParameter
```

According to the documentation, in the absence of a syntax declaration:
> kubetpl assumes that template is a regular resource definition file

But it seems that it's maybe actually trying to render it as `template-kind`?

A workaround is to add `# kubetpl:syntax:$` and, in this case, it renders as expected.
