### ISSUE TITLE
BUG: --freeze says 'Malformed object (missing/invalid kind)' with valid yaml and kubernetes resource

### ISSUE THREAD

**Issue by krbcmt** [shyiko/kubetpl#36]
--freeze can't handle yaml files that start with yaml's `---`, the [c-document-start](https://yaml.org/spec/1.1/#c-document-start) boundary marker. Without --freeze `render` handles the yaml with or without the boundary marker.

```
❯ cat configmap.template
# kubetpl:syntax:go-template
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .APP }}-config
  namespace: {{ .NAMESPACE }}
data:
  my-key: my-value

❯ ./kubetpl-0.9.0-linux-amd64 render configmap.template --freeze --set APP=my-app --set NAMESPACE=default
---
apiVersion: v1
data:
  my-key: my-value
kind: ConfigMap
metadata:
  name: my-app-config-3b45d2a
  namespace: default

❯ vi configmap.template #Add --- to the top of the yaml block

❯ cat configmap.template
# kubetpl:syntax:go-template
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .APP }}-config
  namespace: {{ .NAMESPACE }}
data:
  my-key: my-value

❯ ./kubetpl-0.9.0-linux-amd64 render configmap.template --freeze --set APP=my-app --set NAMESPACE=default
Malformed object (missing/invalid kind)

```
