### ISSUE TITLE
24:22: "REGISTRY" isn't set

### ISSUE THREAD

**Issue by k1ng440** [shyiko/kubetpl#4]
Hello,
i am keep getting error

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: $NAME
spec:
  replicas: $REPLICAS

  template:
    metadata:
      labels:
        app: $NAME-srv
    spec:
      containers:
        - name: $NAME
          command: [
            "/$NAME-srv",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
          ]
          image: microhq/$NAME-srv:kubernetes
          env:
            - name: MICRO_REGISTRY
              value: $REGISTRY
            - name: MICRO_TRANSPORT
              value: $TRANSPORT
            - name: MICRO_SELECTOR
              value: $SELECTOR
            - name: MICRO_REDIS_ADDRESS
              value: $REDIS_ADDRESS
            - name: MICRO_REDIS_PASSWORD
              value: $REDIS_PASSWORD
            - name: MICRO_REDIS_DATABASE
              value: $REDIS_DATABASE
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: $NAME-port
        - name: health
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=$NAME",
            "--server_address=0.0.0.0:8080"
          ]
          image: microhq/health:kubernetes
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
```

env: 
```
NAME=account
EXECUTABLE=account-srv
REPLICAS=1
BROKER=nats
REGISTRY=kubernetes
TRANSPORT=nats
SELECTOR=static
REDIS_ADDRESS=my-release-redis-master:6379
REDIS_PASSWORD=""
REDIS_DATABASE=0
```

kubetpl render deployment.tpl -i production.env --syntax=$
