### ISSUE TITLE
messed up rendering

### ISSUE THREAD

**Issue by k1ng440** [shyiko/kubetpl#6]
kubectl logs calc-fnc-5b7d48c9bb-dlwd9
Error from server (BadRequest): a container name must be specified for pod calc-fnc-5b7d48c9bb-dlwd9, choose one of: [calc-fnc health]

```
# kubetpl:syntax:$

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: $NAME
spec:
  replicas: $REPLICAS

  template:
    metadata:
      labels:
        app: $EXECUTABLE
    spec:
      serviceAccountName: micro-services
      containers:
        - name: $NAME
          command: [
            "/$EXECUTABLE",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
          ]
          image: $IMAGE
          env:
            - name: MICRO_REGISTRY
              value: $REGISTRY
            - name: MICRO_TRANSPORT
              value: $TRANSPORT
            - name: MICRO_SELECTOR
              value: $SELECTOR
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: $NAME-port
        - name: health
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=$NAME",
            "--server_address=0.0.0.0:8080"
          ]
          image: microhq/health:kubernetes
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
```

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calc-fnc
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: calculation-srv
    spec:
      containers:
      - command:
        - /calculation-srv
        - --server_address=0.0.0.0:8080
        - --broker_address=0.0.0.0:10001
        env:
        - name: MICRO_REGISTRY
          value: kubernetes
        - name: MICRO_TRANSPORT
          value: nats
        - name: MICRO_SELECTOR
          value: static
        image: cryptovalue/calculation-fnc:221f746
        imagePullPolicy: Always
        name: calc-fnc
        ports:
        - containerPort: 8080
          name: calc-fnc-port
      - command:
        - /health
        - --health_address=0.0.0.0:8081
        - --server_name=calc-fnc
        - --server_address=0.0.0.0:8080
        image: microhq/health:kubernetes
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        name: health
      serviceAccountName: micro-services
```
